version: '3.6'
services:

  mysite:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html5up-stellar/:/data/www # Static content
    networks:
      - backend

  attacker:
    image: utkudarilmaz/hping3:latest
    command: 'mysite -p 80'
    depends_on:
      - mysite
    networks:
      - backend

networks:
  backend:
    driver: bridge
